version: v31
data_local_save_dir: ./data/raw
dvc_remote_repo: https://github.com/Charleschua/cyberbully-data.git
dvc_data_folder: data/raw
github_user_name: Charleschua
github_access_token_secret_id: cyberbully-data-github-access-token
infrastructure:
  project_id: cyberbully-data-preparation
  zone: asia-southeast1-a
  network: default
dataset_reader_manager:
  _target_: cybulde.data_processing.dataset_readers.DatasetReaderManager
  dataset_readers:
    ghc:
      _target_: cybulde.data_processing.dataset_readers.GHCDatasetReader
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      gcp_project_id: cyberbully-data-preparation
      gcp_github_access_token_secret_id: cyberbully-data-github-access-token
      dvc_remote_repo: https://github.com/Charleschua/cyberbully-data.git
      github_user_name: Charleschua
      version: v31
      dev_split_ratio: 0.3
    jtc:
      _target_: cybulde.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      dataset_dir: ./data/raw/jigsaw-toxic-comments
      dataset_name: jtc
      gcp_project_id: cyberbully-data-preparation
      gcp_github_access_token_secret_id: cyberbully-data-github-access-token
      dvc_remote_repo: https://github.com/Charleschua/cyberbully-data.git
      github_user_name: Charleschua
      version: v31
      dev_split_ratio: 0.03
    twitter:
      _target_: cybulde.data_processing.dataset_readers.TwitterDatasetReader
      dataset_dir: ./data/raw/twitter
      dataset_name: twitter
      gcp_project_id: cyberbully-data-preparation
      gcp_github_access_token_secret_id: cyberbully-data-github-access-token
      dvc_remote_repo: https://github.com/Charleschua/cyberbully-data.git
      github_user_name: Charleschua
      version: v31
      dev_split_ratio: 0.125
      test_split_ratio: 0.1
  repartition: true
  available_memory: 3750000000.0
dataset_cleaner_manager:
  _target_: cybulde.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    stop_words:
      _target_: cybulde.data_processing.dataset_cleaners.StopWordsDatasetCleaner
    to_lower_case:
      _target_: cybulde.data_processing.dataset_cleaners.ToLowerCaseDatasetCleaner
    url:
      _target_: cybulde.data_processing.dataset_cleaners.URLDatasetCleaner
    punctuation:
      _target_: cybulde.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    non_letters:
      _target_: cybulde.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    new_line:
      _target_: cybulde.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: cybulde.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    referance:
      _target_: cybulde.data_processing.dataset_cleaners.ReferanceToAccountDatasetCleaner
    re_tweet:
      _target_: cybulde.data_processing.dataset_cleaners.ReTweetDatasetCleaner
dask_cluster:
  _target_: dask.distributed.LocalCluster
  n_workers: 4
  memory_limit: auto
  processes: true
  threads_per_worker: 1
  scheduler_port: 8786
  silence_logs: 30
  host: null
  dashboard_address: :8787
  asynchronous: false
  blocked_handlers: null
  service_kwargs: null
  security: null
  protocol: null
  interface: null
  worker_class: null
processed_data_save_dir: gs://cyberbully-bucket-3/data/processed/default_run
run_tag: default_run
docker_image_name: asia-southeast1-docker.pkg.dev/cyberbully-data-preparation/cybulde/cybulde-data-preparation
docker_image_tag: 3bf5cd03-1ca3-4968-a51e-be95d0157978
