version: v31
data_local_save_dir: ./data/raw
dvc_remote_repo: https://github.com/Charleschua/cyberbully-data.git
dvc_data_folder: data/raw
github_user_name: Charleschua
github_access_token_secret_id: cyberbully-data-github-access-token
infrastructure:
  project_id: cyberbully-data-preparation
  zone: asia-southeast1-a
  network: default
dataset_reader_manager:
  _target_: cybulde.data_processing.dataset_readers.DatasetReaderManager
  dataset_readers:
    ghc:
      _target_: cybulde.data_processing.dataset_readers.GHCDatasetReader
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      gcp_project_id: cyberbully-data-preparation
      gcp_github_access_token_secret_id: cyberbully-data-github-access-token
      dvc_remote_repo: https://github.com/Charleschua/cyberbully-data.git
      github_user_name: Charleschua
      version: v31
      dev_split_ratio: 0.3
    jtc:
      _target_: cybulde.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      dataset_dir: ./data/raw/jigsaw-toxic-comments
      dataset_name: jtc
      gcp_project_id: cyberbully-data-preparation
      gcp_github_access_token_secret_id: cyberbully-data-github-access-token
      dvc_remote_repo: https://github.com/Charleschua/cyberbully-data.git
      github_user_name: Charleschua
      version: v31
      dev_split_ratio: 0.03
    twitter:
      _target_: cybulde.data_processing.dataset_readers.TwitterDatasetReader
      dataset_dir: ./data/raw/twitter
      dataset_name: twitter
      gcp_project_id: cyberbully-data-preparation
      gcp_github_access_token_secret_id: cyberbully-data-github-access-token
      dvc_remote_repo: https://github.com/Charleschua/cyberbully-data.git
      github_user_name: Charleschua
      version: v31
      dev_split_ratio: 0.125
      test_split_ratio: 0.1
  repartition: true
  available_memory: 3750000000.0
dataset_cleaner_manager:
  _target_: cybulde.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    stop_words:
      _target_: cybulde.data_processing.dataset_cleaners.StopWordsDatasetCleaner
    to_lower_case:
      _target_: cybulde.data_processing.dataset_cleaners.ToLowerCaseDatasetCleaner
    url:
      _target_: cybulde.data_processing.dataset_cleaners.URLDatasetCleaner
    punctuation:
      _target_: cybulde.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    non_letters:
      _target_: cybulde.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    new_line:
      _target_: cybulde.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: cybulde.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    referance:
      _target_: cybulde.data_processing.dataset_cleaners.ReferanceToAccountDatasetCleaner
    re_tweet:
      _target_: cybulde.data_processing.dataset_cleaners.ReTweetDatasetCleaner
dask_cluster:
  _target_: dask_cloudprovider.gcp.GCPCluster
  n_workers: 3
  projectid: cyberbully-data-preparation
  zone: asia-southeast1-a
  network: default
  network_projectid: cyberbully-data-preparation
  machine_type: n1-standard-1
  source_image: projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2004-focal-v20220203
  docker_image: asia-southeast1-docker.pkg.dev/cyberbully-data-preparation/cybulde/cybulde-data-preparation:90cf5eae-4d26-4296-8939-273e7850fb92
  docker_args: '--log-driver=gcplogs

    '
  extra_bootstrap:
  - gcloud auth configure-docker --quiet asia-southeast1-docker.pkg.dev
  ngpus: 0
  gpu_type: null
  filesystem_size: 50
  disk_type: pd-standard
  on_host_maintenance: TERMINATE
  worker_class: dask.distributed.Nanny
  worker_options:
    nthreads: 1
  env_vars: {}
  scheduler_options: {}
  silence_logs: null
  asynchronous: null
  security: true
  preemptible: false
  debug: false
  instance_labels: null
processed_data_save_dir: gs://cyberbully-bucket-3/data/processed/default_run
run_tag: default_run
docker_image_name: asia-southeast1-docker.pkg.dev/cyberbully-data-preparation/cybulde/cybulde-data-preparation
docker_image_tag: 90cf5eae-4d26-4296-8939-273e7850fb92
